//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natom.Extensions.Mailer {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTemplates() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Natom.Extensions.Mailer.ResourceTemplates", typeof(ResourceTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///	&lt;body style=&quot;background-color:#212324;color:#cbcbcb; font-family:&apos;Courier New&apos;,SFMono-Regular,Menlo,Monaco,Consolas;Arial&quot;&gt;
        ///		&lt;br/&gt;
        ///		&lt;table width=&quot;100%&quot;&gt;
        ///			&lt;tr height=&quot;40&quot;&gt;
        ///				&lt;center&gt;
        ///					&lt;h1&gt;
        ///						&lt;b style=&quot;color: #770bbc;&quot;&gt;Bio&lt;/b&gt;&lt;b style=&quot;color: #11579d;&quot;&gt;Anviz&lt;/b&gt;&amp;nbsp;&lt;b style=&quot;color: #037f81;&quot;&gt;+&lt;/b&gt;
        ///					&lt;/h1&gt;
        ///				&lt;/center&gt;
        ///			&lt;/tr&gt;
        ///			&lt;tr&gt;
        ///			
        ///			&lt;/tr&gt;
        ///		&lt;/table&gt;
        ///		&lt;br/&gt;
        ///		$body$
        ///	&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
    }
}
